
var $ = function(id) {return document.getElementById(id);};
$("coldTemp").innerHTML = "1&#176;F";
$("hotTemp").innerHTML = "2&#176;F";
$("coldHum").innerHTML = "3%";
$("hotHum").innerHTML = "4%";
$("headStat").innerHTML = "5";
$("time").innerHTML = "7";
$("inputLowTemp").value = "80";
$("inputHighTemp").value = "85";
$("heaterStatus").checked = true;
$("dayRed").value = 255;
$("dayGreen").value = 255;
$("dayBlue").value = 255;
$("nightRed").value = 0;
$("nightGreen").value = 0;
$("nightBlue").value = 75;
$("morning").value = 8;
$("evening").value = 20;
